<div align="center"><font size="6">CS345: Quiz 2</font></div>

**Instructions**

Download this notebook and edit it.  Start by replacing the text in the following markdown cell with your name.  When you have completed the quiz, submit it in Canvas.

**Ryan Blocker**

### Question 1

For the given list 
    
    A = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] 
    
write a code that produces each of the desired output lists: 

1. A1 = [3, 4, 5]

1. A2 = [1, 3, 5, 7]

1. A3 = [8, 7, 6]

1. A4 = [10, 7, 4]

1. A5 = [3, 8, 1, 3]


Note: edit the code cell below to implement the code. **Please have one line of code per list.**

In [1]:
A = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] 
    
A1 = A[2:5]

A2 = A[0::2][:4]

A3 = A[-3::-1][:3]

A4 = A[-1:-8:-3]

A5 = [A[i] for i in [2, 7, 0, 2]]


In [2]:
print("A1 =",A1)
print("A2 =",A2)
print("A3 =",A3)
print("A4 =",A4)
print("A5 =",A5)

A1 = [3, 4, 5]
A2 = [1, 3, 5, 7]
A3 = [8, 7, 6]
A4 = [10, 7, 4]
A5 = [3, 8, 1, 3]


### Question 2

For the given NumPy array 
    
    [[1 2 3]
     [4 5 6]
     [7 8 9]]
    
write a code that produces each of the desired output arrays as shown here:

```
B1 = 
 [2 5 8]

B2 = 
 [[1]
  [4]
  [7]]

B3 = 
 [1 2 3 7 8 9]

B4 = 
 [[1 2]
  [4 5]
  [7 8]]

B5 = 
 [[2 3]
  [8 9]]

B6 = 
 [[1]
  [2]
  [3]
  [4]
  [5]
  [6]
  [7]
  [8]
  [9]]
  
B7 = 
 [[1 1 2 3]
  [1 4 5 6]
  [1 7 8 9]]

B8 = 
 [[1 0 2 3]
  [4 0 5 6]
  [7 0 8 9]]

B9 = 
 [[10 12]
  [25 24]
  [40 36]]

B10 = 
 [[ 1  8 21]
  [ 4 20 42]
  [ 7 32 63]]
```


Note: edit the code cell below to implement the code. You can only use indexing, `reshape()`, `flatten()` or `insert()` for `B1` through `B8`.  For `B9` and `B10` use indexing and multiplication `*`.

**Please have one line of code per array.**

In [3]:
import numpy as np

B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

B1 = B[:, 1]

B2 = B[:, 0].reshape(-1, 1)

B3 = B[[0,2]].flatten()

B4 = B[:, 0:2]

B5 = B[0::2, 1:]

B6 = B.flatten().reshape(-1, 1)

B7 = np.insert(B, 0, 1, axis=1)

B8 = np.insert(B, 1, 0, axis=1)

B9 = np.hstack([(B[:,[1]]*5) , (B[:,[2]]*4)])

B10 = np.hstack([(B[:,[0]]*1) , (B[:,[1]]*4) , (B[:,[2]]*7)])

In [4]:
print("B1 = \n", B1)
print("B2 = \n", B2)
print("B3 = \n", B3)
print("B4 = \n", B4)
print("B5 = \n", B5)
print("B6 = \n", B6)
print("B7 = \n", B7)
print("B8 = \n", B8)
print("B9 = \n", B9)
print("B10 = \n", B10)

B1 = 
 [2 5 8]
B2 = 
 [[1]
 [4]
 [7]]
B3 = 
 [1 2 3 7 8 9]
B4 = 
 [[1 2]
 [4 5]
 [7 8]]
B5 = 
 [[2 3]
 [8 9]]
B6 = 
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
B7 = 
 [[1 1 2 3]
 [1 4 5 6]
 [1 7 8 9]]
B8 = 
 [[1 0 2 3]
 [4 0 5 6]
 [7 0 8 9]]
B9 = 
 [[10 12]
 [25 24]
 [40 36]]
B10 = 
 [[ 1  8 21]
 [ 4 20 42]
 [ 7 32 63]]


### Question 3

Let's assume we are implementing a classification model that has 3 distinct classes `[2, 5, 15]`. Write code to create indicator variable `Tiv` for this case. 

Shortly explain the advantage of using indicator variables as output compared to a single value prediction in this case?  

In [5]:
def make_indicator_vars(T):
    return (T.reshape(-1,1) == np.array(classes)).astype(int)

classes = np.array([2, 5, 15])
Tiv = make_indicator_vars(classes)
print('indicator variable values are: \n', Tiv)

indicator variable values are: 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


**Explanation:** The advantage of using indicator variables as output compared to a single value prediction is that it allows the model to predict the probability of an instance belonging to each class. This can be useful in cases where the dividing line between classes is not clear, or when multiple classes are valid for a given input. Indicator variables also give us more info about each input, and allow us to evaluate the performance of the model across all classes.

### Question 4

We often pass output of a model through a softmax function. Shortly describe why we do this.

Hint: probabilities are always in the range `[0,1]` and take into account that we use indicator variables that are arrays with one `1` value and the rest values are `0`.

**Answer:** We pass outputs through softmax because we need to convert the output of a model into a probability distribution over the classes.The softmax function make sure that the output probabilities are in the range of 0-1 which makes it easier to interpret and compare the model's predictions.

### Question 5


For a simple weight matrix `W = [W1, W2]` for input `X = [X1, X2]` the output `Y` of a simple model can be written as: 
    
    Y = X1 * W1 + X2 * W2
    
By adding  a column of `1`s to the input and an additional weights column `W0` to our weight matrix `W`, our simple model becomes: 

    Y_with_bias = 1 * W0 + X1 * W1 + X2 * W2
    
where `1` is an array of ones with dimension `(N, 1)` and `N = X.shape[0]` is the number of rows or  data samples in `X`.

What is the reasoning behind adding bias to our model? 

Note: you can also think in terms of plotting `Y` and `Y_with_bias` on a 2-dimensional plot. Think in what ways they differ and if one of them is more powerful function to capture data (and why). 

**Answer:** We add bias term to our models because we need to introduce an intercept term, that is independent from the input variables. This is important because it allows the model to fit the data even when the input variables have a value of zero. In other words, adding bias allows our model to shift the output away from the origin, which can be important in certain cases where the origin may not be a good fit for the data. In terms of plotting Y and Y_with_bias on a two dimensional plot, adding bias would shift the function along the y-axis, allowing it to better fit the data. This is important when the relationship between the input and output is not linear. A linear function with no bias would not be able to fit the data that good.

### Question 6

Let's assume we want to create a machine learning model for a data set that has 10 samples and 5 features in each sample. The data has 3 distinct classes.  

In the cell below define `Sympy` matrices for the input data `X` and the weight matrix `W`. Make sure to include bias term. 

In [6]:
import sympy as sp

n_samples = 10

n_features = 5

n_outputs = 3


X = sp.Matrix(sp.MatrixSymbol('X', n_samples, n_features+1))
    
W = sp.Matrix(sp.MatrixSymbol('W', n_features+1, n_outputs))


In [7]:
print('X = \n')
X

X = 



Matrix([
[X[0, 0], X[0, 1], X[0, 2], X[0, 3], X[0, 4], X[0, 5]],
[X[1, 0], X[1, 1], X[1, 2], X[1, 3], X[1, 4], X[1, 5]],
[X[2, 0], X[2, 1], X[2, 2], X[2, 3], X[2, 4], X[2, 5]],
[X[3, 0], X[3, 1], X[3, 2], X[3, 3], X[3, 4], X[3, 5]],
[X[4, 0], X[4, 1], X[4, 2], X[4, 3], X[4, 4], X[4, 5]],
[X[5, 0], X[5, 1], X[5, 2], X[5, 3], X[5, 4], X[5, 5]],
[X[6, 0], X[6, 1], X[6, 2], X[6, 3], X[6, 4], X[6, 5]],
[X[7, 0], X[7, 1], X[7, 2], X[7, 3], X[7, 4], X[7, 5]],
[X[8, 0], X[8, 1], X[8, 2], X[8, 3], X[8, 4], X[8, 5]],
[X[9, 0], X[9, 1], X[9, 2], X[9, 3], X[9, 4], X[9, 5]]])

In [8]:
print('W = \n')
W

W = 



Matrix([
[W[0, 0], W[0, 1], W[0, 2]],
[W[1, 0], W[1, 1], W[1, 2]],
[W[2, 0], W[2, 1], W[2, 2]],
[W[3, 0], W[3, 1], W[3, 2]],
[W[4, 0], W[4, 1], W[4, 2]],
[W[5, 0], W[5, 1], W[5, 2]]])



### Question 7

Now use NumPy to create input data array `X` and weights array `W` for the same model from Q6. You can fill the arrays with any values though the weights must be in the range `[-1, 1]`. Don't forget to add the bias term.


In [13]:
n_samples = 10

n_features = 5

n_outputs = 3


W = np.random.uniform(-1,1, size=(n_features+1, n_outputs))

X = np.random.uniform(-1,1, size=(n_samples, n_features))

X1 = np.hstack((np.ones((n_samples, 1)), X))

print('X1 has shape ', X1.shape,' and X = \n',X)
print('W has shape ', W.shape,' and W = \n',W)

X1 has shape  (10, 6)  and X = 
 [[ 0.85627066 -0.37486509  0.23285454 -0.34581106 -0.61058051]
 [ 0.59189204 -0.48122012 -0.8048604  -0.38421794 -0.34315802]
 [-0.98070305  0.77104242  0.79341827  0.03746582  0.64117437]
 [ 0.42025658  0.72996036  0.86842443  0.91936217  0.91021392]
 [ 0.57042709 -0.79892271  0.95593713  0.76664332  0.53832994]
 [ 0.1294535   0.99174911 -0.26647083 -0.36987266  0.47705314]
 [ 0.29960497 -0.90096357  0.49903851 -0.18590119 -0.87961405]
 [-0.09543967 -0.74863157 -0.85798018 -0.63198753 -0.89663818]
 [ 0.20372281 -0.68707125 -0.08003273  0.31397183  0.69324954]
 [ 0.89370726  0.92587115 -0.18110177  0.08656861 -0.43296889]]
W has shape  (6, 3)  and W = 
 [[ 0.53122866 -0.83631484  0.58959134]
 [-0.53979667 -0.01771125  0.86878857]
 [ 0.36705271 -0.49752797 -0.24246226]
 [-0.05685295  0.87735434 -0.2724421 ]
 [-0.06581252  0.24655139  0.55714113]
 [-0.36518983 -0.20791234 -0.15452987]]


### Question 8

Now that we have input and weight matrices, a simple model will calculate the output by multiplying the input after adding the bias term `X1` with the weight matrix `W`

Write one line of code that will perform this operation. 

Does the order of `X1` and `W` in the multiplication matter? Why or why not?

What will be the dimensions of the output array `Y`? What will $Y_{5,1}$ refer to?

In [14]:
Y = X1 @ W

print("Y has dimensions:", Y.shape, " and Y = \n", Y)

Y has dimensions: (10, 3)  and Y = 
 [[ 0.16391939 -0.41899163  1.26264812]
 [ 0.23145701 -1.33690797  1.27874051]
 [ 1.06189786 -0.63052238 -0.74374833]
 [ 0.13003058 -0.40759255  0.91268147]
 [-0.37132792  0.4668557   1.36238343]
 [ 0.69065123 -1.75619774  0.25440497]
 [ 0.3438907   0.18151539  0.96472872]
 [ 0.72577397 -1.18430724  0.70839041]
 [-0.10021247 -0.63502787  1.02277538]
 [ 0.55136667 -1.36031756  1.30602248]]


**Answer:** 

The order of `X1` and `W` is following the communitive law of math (MxN * NxQ = MxQ). If you switched the order the shape would be incorrect for Y if you multiplied W @ X1. 

The output array `Y` will have dimensions of (10, 3)

$Y_{5,1}$ refers to to 5th row and first column of Y. It is the output for the 5th sample and first output feature. 

### Question 9

Write three nested `for` loops that compute the same result as your answer to Question 8 only using scalar multiplications with `*`.  Compute your answer as `Y2`. The test for equality below must return `True`.


In [15]:
# YOUR CODE IN MULTIPLE LINES

Y2 = np.zeros((n_samples, n_outputs))

for sample_i in range(n_samples):
    for output_i in range(n_outputs):
        for features_i in range(n_features+1):
            Y2[sample_i, output_i] += X1[sample_i, features_i] * W[features_i, output_i]
            
print(np.all(np.abs(Y2 - Y) < 1e-8))  # must print True


True
